spring:
  application:
    name: event
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/apollo

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8083/eureka

management:
  endpoints:
    web:
      exposure:
        include: promotheus

server:
  port: 8084