services:
  ##Event microservice
  event:
    image: event
    build:
      context: .\backend\microservices-apollo\event
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  ##Notification microservice
  notification:
    image: notification
    build:
      context: .\backend\microservices-apollo\notification
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - postgres


  ##User micorservice
  user:
    image: user
    build:
      context: .\backend\microservices-apollo\user
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    depends_on:
      - postgres


  ##Model microservice
  models:
    image: model
    build:
      context: .\backend\microservices-apollo\models
      dockerfile: Dockerfile
    ports:
      - 8084:8084

  postgres:
    container_name: postgres1
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - .\prometheus\prometheus.yml:\etc\prometheus\prometheus.yml
    depends_on:
      - notification
      - models
      - event
      - user
    user: "0:0"

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - .\grafana:\var\lib\grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: